import random

def jugar_juego():
    print("Bienvenido al juego de magia!")
    print("Piensa en un número del 1 al 100 y yo trataré de adivinarlo.")

    numero_secreto = random.randint(1, 100)
    intentos = 0
    acertado = False

    while not acertado:
        intentos += 1
        adivinanza = random.randint(1, 100)
        print("¿Es este tu número?:", adivinanza)

        respuesta = input("¿Es correcto? (s/n): ")
        if respuesta == "s":
            acertado = True
        elif respuesta == "n":
            pista = input("¿Es el número mayor o menor? (mayor/menor): ")
            if pista == "mayor":
                adivinanza = random.randint(adivinanza + 1, 100)
            elif pista == "menor":
                adivinanza = random.randint(1, adivinanza - 1)
        else:
            print("Respuesta no válida. Por favor, responde con 's' o 'n'.")

    print(f"Adiviné tu número en {intentos} intentos. ¡Eso es magia!")

jugar_juego()
