import random

class Tank:
    def __init__(self, name):
        self.name = name
        self.health = 100
        self.damage = 20

    def attack(self, target):
        target.health -= self.damage
        print(f"{self.name} ataca a {target.name} y le causa {self.damage} puntos de daño.")
        if target.health <= 0:
            print(f"{target.name} ha sido destruido.")

    def is_alive(self):
        return self.health > 0


def main():
    player_tank = Tank("Jugador")
    enemy_tank = Tank("Enemigo")

    while player_tank.is_alive() and enemy_tank.is_alive():
        print(f"{player_tank.name}: {player_tank.health} de salud")
        print(f"{enemy_tank.name}: {enemy_tank.health} de salud")
        print("")

        # Turno del jugador
        player_choice = input("¿Qué quieres hacer? (a = atacar, s = salir): ")
        if player_choice == "a":
            player_tank.attack(enemy_tank)
        elif player_choice == "s":
            print("Has decidido salir del juego.")
            break
        else:
            print("Opción inválida. Intenta de nuevo.")

        # Turno del enemigo
        enemy_choice = random.choice(["a", "s"])
        if enemy_choice == "a":
            enemy_tank.attack(player_tank)
        elif enemy_choice == "s":
            print("El enemigo ha decidido salir del juego.")
            break

    print("Juego terminado.")

if __name__ == "__main__":
    main()
